TARGET_NO_KERNEL := true
TARGET_NO_BOOTLOADER := true

OMAP_ENHANCEMENT := true
OMAP_ENHANCEMENT_MULTIGPU := true
ENHANCED_DOMX := true
BLTSVILLE_ENHANCEMENT :=true
BOARD_USES_DVP := true
BOARD_USES_ARX := true

TARGET_ARCH := arm
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_CPU_SMP := true
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_VARIANT := cortex-a9
ARCH_ARM_HAVE_TLS_REGISTER := true


TARGET_BOARD_PLATFORM := omap4

TARGET_NO_RADIOIMAGE := true
TARGET_BOOTLOADER_BOARD_NAME := libz500


BOARD_USES_GENERIC_AUDIO := true
USE_CAMERA_STUB := true

BOARD_EGL_CFG := device/sciaps/libz500/egl.cfg

USE_OPENGL_RENDERER := true

include device/ti/common-open/BoardConfig.mk